Class {
	#name : 'Rowan3LoadedClassExtensionStub',
	#superclass : 'Object',
	#instVars : [
		'theClass'
	],
	#category : 'RowanStubForJadeite-Core'
}

{ #category : 'accessing' }
Rowan3LoadedClassExtensionStub >> handle [
	^ self theClass
]

{ #category : 'accessing' }
Rowan3LoadedClassExtensionStub >> theClass [
	^theClass
]

{ #category : 'accessing' }
Rowan3LoadedClassExtensionStub >> theClass: object [
	theClass := object
]
